# Databricks notebook source
# COMMAND ----------
# MAGIC %md
# MAGIC # Step 7: Add All Table and Column Comments
# MAGIC Applies semantic COMMENT ON TABLE and ALTER TABLE ... ALTER COLUMN COMMENT for every table and column.

# COMMAND ----------
dbutils.widgets.text("catalog_name", "GAP_Demo_Dev", "Catalog Name")
CATALOG = dbutils.widgets.get("catalog_name")

# COMMAND ----------
# ---- Table Comments ----
table_comments = {
    f"{CATALOG}.demand_analysis.products": "Product catalog with SKU details, product families (Apparel, Accessories, Footwear, Home Goods, Electronics), categories, unit costs and prices. 100 SKUs.",
    f"{CATALOG}.demand_analysis.customer_segments": "Customer master with 500 customers. Segment types: Premium, Standard, Value, Wholesale. Includes region, loyalty score, revenue tier.",
    f"{CATALOG}.demand_analysis.sales_orders": "Sales order transactions with revenue, fulfillment status by region. 90 days of history. Key columns: order_date, region, product_family, total_amount, order_status.",
    f"{CATALOG}.demand_analysis.demand_forecasts": "Monthly demand forecasts vs actuals by region and product family. Tracks forecast_accuracy_pct and bias. 6 months of history.",
    f"{CATALOG}.demand_analysis.pos_data": "Point-of-sale transactions from 80 retail stores. Daily sales with store, SKU, revenue details. 60 days of history.",
    f"{CATALOG}.demand_analysis.promotions": "30 promotional campaigns with discount details, target regions, budget, and actual vs estimated lift percentages.",
    f"{CATALOG}.inventory_management.warehouse_data": "12 warehouses (3 per region). Includes capacity, utilization percentage, type. WH-001 to 003=Western, 004-006=Eastern, 007-009=Central, 010-012=Southern.",
    f"{CATALOG}.inventory_management.inventory_ledger": "Current inventory snapshot per warehouse per SKU. Tracks on_hand_qty, safety_stock_level, days_of_supply, stockout_flag, below_safety_stock_flag.",
    f"{CATALOG}.inventory_management.store_inventory": "Store-level inventory for 80 stores with replenishment_status (Stockout/Low/Adequate) per SKU.",
    f"{CATALOG}.inventory_management.stock_movements": "Inbound/outbound stock movements over 60 days. Positive quantity = inbound, negative = outbound. Tracks movement_type and reason_code.",
    f"{CATALOG}.logistics_operations.carriers": "8 carriers with type (LTL/FTL/Parcel/Expedited), on-time rates, avg transit days, cost per mile.",
    f"{CATALOG}.logistics_operations.distribution_centers": "7 distribution centers with capacity, current load percentage, dock doors. LA Hub (DC-W1) at 92.3% load.",
    f"{CATALOG}.logistics_operations.shipments": "Shipment records. IMPORTANT: Uses destination_region and origin_region (NOT region). is_late=true when actual_transit_days > planned_transit_days. 90 days.",
    f"{CATALOG}.logistics_operations.transit_data": "Shipment tracking events: Picked_Up, In_Transit, At_Hub, Out_For_Delivery, Delivered, Exception. Join to shipments on shipment_id.",
    f"{CATALOG}.supplier_procurement.suppliers": "12 suppliers across Asia, Europe, North America. Includes risk_tier (High/Medium/Low), reliability_score, annual contract value.",
    f"{CATALOG}.supplier_procurement.supplier_orders": "Purchase orders with contracted vs actual lead times. is_late=true when actual exceeds contracted. 120 days of history.",
    f"{CATALOG}.supplier_procurement.supplier_lead_times": "Monthly supplier lead time trends: contracted vs actual, on-time delivery rates, defect rates. 12 months.",
    f"{CATALOG}.supplier_procurement.vendor_slas": "SLA compliance per supplier. Metrics: On_Time_Delivery, Quality_Acceptance, Fill_Rate, Response_Time, Documentation_Accuracy. is_breached=true when below target.",
    f"{CATALOG}.supplier_procurement.procurement_data": "Monthly procurement spend by product family with budget variance, supplier count, geographic concentration risk.",
    f"{CATALOG}.reporting.regional_performance_summary": "Cross-domain regional view combining revenue, inventory stockouts, logistics delays, and supplier late rates per region.",
    f"{CATALOG}.reporting.revenue_trend": "Daily revenue aggregated by region and product family with period classification: Last_30_Days, Prior_30_Days, Older.",
    f"{CATALOG}.reporting.supply_chain_risk_scorecard": "Supplier risk ranking with composite score from lead time variance, SLA breaches, quality, and on-time delivery. Lower score = higher risk.",
    f"{CATALOG}.reporting.executive_kpis": "Single-row executive KPI view: revenue trend, stockout count, late delivery %, supplier late %, SLA breaches, service level %.",
}

for table, comment in table_comments.items():
    safe_comment = comment.replace("'", "\\'")
    spark.sql(f"COMMENT ON TABLE {table} IS '{safe_comment}'")
print(f"✓ {len(table_comments)} table comments applied")

# COMMAND ----------
# ---- Column Comments ----
# Dictionary: {table: {column: comment}}
column_comments = {
    # ========== DEMAND ANALYSIS ==========
    f"{CATALOG}.demand_analysis.sales_orders": {
        'order_id': 'Unique order identifier (ORD-XXXXXX)',
        'order_date': 'Date the order was placed (YYYY-MM-DD). Use for time-based filtering.',
        'customer_id': 'Foreign key to customer_segments table (CUST-XXXXX)',
        'region': 'Geographic region: Western, Eastern, Central, Southern',
        'state': 'US state abbreviation (CA, NY, TX, etc.)',
        'sku_id': 'Foreign key to products table (SKU-XXXX)',
        'product_family': 'Top-level product grouping: Apparel, Accessories, Footwear, Home Goods, Electronics',
        'product_category': 'Sub-category within product family',
        'quantity': 'Number of units ordered',
        'unit_price': 'Price per unit in USD',
        'total_amount': 'Total order value in USD (quantity * unit_price). Primary revenue metric.',
        'order_status': 'Fulfillment status: Fulfilled, Partially_Fulfilled, Backordered, Cancelled',
        'channel': 'Sales channel: Online, Retail, Wholesale, Marketplace',
        'fulfillment_warehouse': 'Warehouse that fulfilled the order (WH-XXX)',
    },
    f"{CATALOG}.demand_analysis.demand_forecasts": {
        'forecast_id': 'Unique forecast record ID (FC-XXXXX)',
        'forecast_month': 'First day of the forecast month (YYYY-MM-DD)',
        'region': 'Geographic region: Western, Eastern, Central, Southern',
        'product_family': 'Product family: Apparel, Accessories, Footwear, Home Goods, Electronics',
        'forecast_demand_units': 'Predicted demand in units for the month',
        'actual_demand_units': 'Actual realized demand in units',
        'forecast_accuracy_pct': 'Forecast accuracy as percentage (0-100). Higher is better.',
        'forecast_model': 'Model used: ARIMA, Prophet, or ML_Ensemble',
        'bias': 'Forecast bias %. Positive = over-forecast, Negative = under-forecast.',
    },
    f"{CATALOG}.demand_analysis.pos_data": {
        'transaction_id': 'Unique POS transaction ID (POS-XXXXXXXX)',
        'transaction_date': 'Date of the POS transaction (YYYY-MM-DD)',
        'store_id': 'Retail store identifier (STORE-XXX)',
        'region': 'Geographic region: Western, Eastern, Central, Southern',
        'sku_id': 'Product SKU identifier (SKU-XXXX)',
        'product_family': 'Product family: Apparel, Accessories, Footwear, Home Goods, Electronics',
        'quantity_sold': 'Number of units sold in this transaction',
        'unit_price': 'Selling price per unit in USD',
        'total_sales': 'Total transaction value in USD (quantity_sold * unit_price)',
        'payment_method': 'Payment type: Credit, Debit, Cash, Digital_Wallet',
        'return_flag': 'True if this transaction was a return',
    },
    f"{CATALOG}.demand_analysis.customer_segments": {
        'customer_id': 'Unique customer identifier (CUST-XXXXX). Foreign key for sales_orders.',
        'customer_name': 'Customer display name',
        'segment': 'Customer segment: Premium, Standard, Value, Wholesale',
        'region': 'Geographic region: Western, Eastern, Central, Southern',
        'state': 'US state abbreviation',
        'city': 'City name',
        'annual_revenue_tier': 'Revenue tier: Tier1_Above1M, Tier2_500K_1M, Tier3_100K_500K, Tier4_Below100K',
        'loyalty_score': 'Customer loyalty score from 1.0 (lowest) to 10.0 (highest)',
        'first_purchase_date': 'Date of first purchase (YYYY-MM-DD)',
        'is_active': 'True if customer is currently active',
    },
    f"{CATALOG}.demand_analysis.products": {
        'sku_id': 'Unique product SKU identifier (SKU-XXXX). FK for sales_orders and pos_data.',
        'product_name': 'Product display name (Category - Style Variant)',
        'product_family': 'Top-level grouping: Apparel, Accessories, Footwear, Home Goods, Electronics',
        'product_category': 'Sub-category within product family',
        'unit_cost': 'Cost to procure one unit in USD',
        'unit_price': 'List selling price per unit in USD',
        'weight_kg': 'Product weight in kilograms',
    },
    f"{CATALOG}.demand_analysis.promotions": {
        'promo_id': 'Unique promotion identifier (PROMO-XXX)',
        'promo_name': 'Promotion name combining type and target family',
        'promo_type': 'Type: Clearance, Seasonal_Sale, Flash_Sale, Loyalty_Discount, Bundle_Deal',
        'start_date': 'Promotion start date (YYYY-MM-DD)',
        'end_date': 'Promotion end date (YYYY-MM-DD)',
        'discount_pct': 'Discount percentage offered (10, 15, 20, 25, or 30)',
        'target_region': 'Region targeted: Western, Eastern, Central, Southern, or All',
        'target_product_family': 'Product family targeted, or All for cross-family promotions',
        'budget_usd': 'Promotion budget in USD',
        'estimated_lift_pct': 'Estimated sales lift percentage from the promotion',
        'actual_lift_pct': 'Actual observed sales lift percentage',
    },
    # ========== INVENTORY MANAGEMENT ==========
    f"{CATALOG}.inventory_management.warehouse_data": {
        'warehouse_id': 'Unique warehouse identifier (WH-XXX). FK for inventory_ledger and shipments.',
        'warehouse_name': 'Descriptive warehouse name (Region DC Number)',
        'region': 'Geographic region: Western, Eastern, Central, Southern',
        'city': 'City where warehouse is located',
        'capacity_units': 'Maximum storage capacity in units',
        'current_utilization_pct': 'Current capacity utilization %. Above 85% = congestion risk.',
        'warehouse_type': 'Warehouse type: Primary, Secondary, or Returns',
        'is_active': 'True if warehouse is currently operational',
    },
    f"{CATALOG}.inventory_management.inventory_ledger": {
        'ledger_id': 'Unique inventory record ID (INV-XXXXXX)',
        'snapshot_date': 'Date of inventory snapshot (YYYY-MM-DD)',
        'warehouse_id': 'Warehouse ID (WH-XXX). WH-001-003=Western, 004-006=Eastern, 007-009=Central, 010-012=Southern.',
        'region': 'Geographic region: Western, Eastern, Central, Southern',
        'sku_id': 'Product SKU identifier (SKU-XXXX)',
        'product_family': 'Product family: Apparel, Accessories, Footwear, Home Goods, Electronics',
        'product_category': 'Sub-category within product family',
        'on_hand_qty': 'Current quantity in warehouse. Zero means stockout.',
        'allocated_qty': 'Quantity allocated to pending orders',
        'available_qty': 'Quantity available for new orders (on_hand minus allocated)',
        'safety_stock_level': 'Minimum inventory threshold. on_hand below this triggers alert.',
        'reorder_point': 'Level at which replenishment order should be placed (2x safety_stock)',
        'days_of_supply': 'Estimated days of inventory remaining. Lower = more urgent.',
        'stockout_flag': 'True when on_hand_qty = 0. COUNT WHERE stockout_flag = true for stockout counts.',
        'below_safety_stock_flag': 'True when on_hand_qty < safety_stock_level. Replenishment urgency.',
    },
    f"{CATALOG}.inventory_management.store_inventory": {
        'store_inventory_id': 'Unique store inventory record ID (SINV-XXXXXX)',
        'snapshot_date': 'Date of store inventory snapshot (YYYY-MM-DD)',
        'store_id': 'Retail store identifier (STORE-XXX)',
        'region': 'Geographic region: Western, Eastern, Central, Southern',
        'sku_id': 'Product SKU identifier (SKU-XXXX)',
        'product_family': 'Product family: Apparel, Accessories, Footwear, Home Goods, Electronics',
        'on_hand_qty': 'Current store shelf quantity',
        'min_display_qty': 'Minimum quantity required for store display',
        'replenishment_status': 'Store status: Stockout (0 units), Low (1-4 units), Adequate (5+)',
        'last_replenishment_date': 'Date of last replenishment (YYYY-MM-DD)',
    },
    f"{CATALOG}.inventory_management.stock_movements": {
        'movement_id': 'Unique movement record ID (MOV-XXXXXXXX)',
        'movement_date': 'Date of stock movement (YYYY-MM-DD)',
        'movement_type': 'Type: Inbound_Receipt, Outbound_Order, Transfer_In, Transfer_Out, Return_Receipt, Adjustment',
        'warehouse_id': 'Warehouse where movement occurred (WH-XXX)',
        'region': 'Geographic region: Western, Eastern, Central, Southern',
        'sku_id': 'Product SKU identifier (SKU-XXXX)',
        'product_family': 'Product family: Apparel, Accessories, Footwear, Home Goods, Electronics',
        'quantity': 'Movement qty. POSITIVE = inbound. NEGATIVE = outbound.',
        'reference_id': 'Reference document ID (REF-XXXXXX)',
        'reason_code': 'Reason: Customer_Order, Replenishment, Rebalance, Damage, Cycle_Count',
    },
    # ========== LOGISTICS OPERATIONS ==========
    f"{CATALOG}.logistics_operations.carriers": {
        'carrier_id': 'Unique carrier ID (CAR-XXX). FK from shipments.',
        'carrier_name': 'Carrier company name',
        'carrier_type': 'Service type: LTL, FTL, Parcel, Expedited',
        'service_regions': 'Regions served: National, or specific regions',
        'on_time_rate_pct': 'Historical on-time delivery rate percentage (0-100)',
        'avg_transit_days': 'Average transit time in days',
        'cost_per_mile': 'Cost per mile in USD',
    },
    f"{CATALOG}.logistics_operations.distribution_centers": {
        'dc_id': 'Distribution center identifier (DC-XX)',
        'dc_name': 'Distribution center name',
        'region': 'Geographic region: Western, Eastern, Central, Southern',
        'state': 'US state abbreviation',
        'city': 'City name',
        'capacity_pallets': 'Maximum pallet storage capacity',
        'current_load_pct': 'Current load % of capacity. Above 85% = congestion risk.',
        'dock_doors': 'Number of loading dock doors',
        'is_cross_dock': 'True if facility supports cross-docking operations',
    },
    f"{CATALOG}.logistics_operations.shipments": {
        'shipment_id': 'Unique shipment ID (SHP-XXXXXXX)',
        'ship_date': 'Date shipment departed origin warehouse (YYYY-MM-DD)',
        'expected_delivery_date': 'Planned delivery date based on planned_transit_days',
        'actual_delivery_date': 'Actual delivery date. NULL if still in transit.',
        'origin_warehouse': 'Origin warehouse ID (WH-XXX)',
        'origin_region': 'Region of origin warehouse. Use destination_region for delivery analysis.',
        'destination_region': 'Destination region. USE THIS (not region) when filtering by region.',
        'destination_state': 'Destination US state abbreviation',
        'carrier_id': 'Carrier ID (CAR-XXX). FK to carriers table.',
        'shipment_type': 'Shipment mode: Full_Truck, LTL, Parcel, Expedited',
        'total_weight_kg': 'Total shipment weight in kilograms',
        'total_pallets': 'Number of pallets in shipment',
        'planned_transit_days': 'Expected transit time in days',
        'actual_transit_days': 'Actual transit time in days',
        'delay_days': 'Days of delay (actual - planned, min 0). Zero = on-time.',
        'is_late': 'True when actual_transit_days > planned_transit_days. Primary late indicator.',
        'shipment_status': 'Status: Delivered, In_Transit, Damaged, Lost',
        'delay_reason': 'Root cause: Port_Congestion, Carrier_Capacity, Weather, Customs_Hold, Labor_Shortage, Warehouse_Congestion',
        'shipping_cost': 'Total shipping cost in USD',
        'order_count': 'Number of customer orders in this shipment',
    },
    f"{CATALOG}.logistics_operations.transit_data": {
        'event_id': 'Unique tracking event ID (EVT-XXXXXXXX)',
        'shipment_id': 'FK to shipments table (SHP-XXXXXXX)',
        'event_timestamp': 'Timestamp of tracking event (YYYY-MM-DD HH:MM:SS)',
        'event_type': 'Event: Picked_Up, In_Transit, At_Hub, Out_For_Delivery, Delivered, Exception, Returned',
        'location': 'Location of event (Hub/Terminal/DC/Station + number)',
        'region': 'Region where event occurred',
        'notes': 'Event description. Contains DELAYED tag for late shipments.',
    },
    # ========== SUPPLIER PROCUREMENT ==========
    f"{CATALOG}.supplier_procurement.suppliers": {
        'supplier_id': 'Unique supplier ID (SUP-XXX). FK for orders, lead_times, SLAs.',
        'supplier_name': 'Supplier company name',
        'country': 'Supplier home country',
        'continent': 'Supplier continent: Asia, Europe, North America. For geographic risk.',
        'primary_product_family': 'Main product family supplied',
        'risk_tier': 'Risk classification: High, Medium, Low',
        'annual_contract_value': 'Annual contract value in USD',
        'reliability_score': 'Reliability score from 1.0 (worst) to 10.0 (best)',
    },
    f"{CATALOG}.supplier_procurement.supplier_orders": {
        'po_id': 'Purchase order ID (PO-XXXXXX)',
        'order_date': 'Date PO was placed (YYYY-MM-DD)',
        'supplier_id': 'FK to suppliers table (SUP-XXX)',
        'supplier_name': 'Supplier company name (denormalized)',
        'supplier_country': 'Supplier country of origin',
        'supplier_continent': 'Supplier continent: Asia, Europe, North America',
        'product_family': 'Product family for this PO',
        'quantity_ordered': 'Units ordered from supplier',
        'quantity_received': 'Units received. Compare to quantity_ordered for fill rate.',
        'unit_cost': 'Cost per unit in USD',
        'total_cost': 'Total PO value in USD (quantity_ordered * unit_cost)',
        'contracted_lead_time_days': 'Contractually agreed delivery time in days',
        'actual_lead_time_days': 'Actual delivery time in days',
        'lead_time_variance_days': 'Days of delay beyond contract. Positive = late.',
        'expected_delivery_date': 'Expected delivery date based on contracted lead time',
        'actual_delivery_date': 'Actual delivery date. NULL if not yet delivered.',
        'is_late': 'True when actual exceeds contracted. Primary supplier delay indicator.',
        'delay_reason': 'Root cause: Port_Strike, Raw_Material_Shortage, Factory_Shutdown, Customs_Delay, Shipping_Congestion',
        'po_status': 'PO status: Received, In_Transit, Partially_Received, Cancelled',
        'quality_score': 'Quality score for received goods (70-100)',
    },
    f"{CATALOG}.supplier_procurement.supplier_lead_times": {
        'lead_time_id': 'Unique lead time record ID (LT-XXXXX)',
        'month': 'First day of month (YYYY-MM-DD). For trend analysis.',
        'supplier_id': 'FK to suppliers table (SUP-XXX)',
        'supplier_name': 'Supplier company name',
        'supplier_country': 'Supplier country',
        'supplier_continent': 'Supplier continent: Asia, Europe, North America',
        'contracted_lead_time_days': 'Contracted lead time in days',
        'avg_actual_lead_time_days': 'Average actual lead time in days for the month',
        'lead_time_variance_days': 'Avg variance in days (actual - contracted). Positive = slower.',
        'on_time_delivery_pct': 'On-time delivery % for the month (0-100)',
        'order_count': 'Number of POs in this monthly aggregation',
        'defect_rate_pct': 'Defect rate as percentage of received goods',
    },
    f"{CATALOG}.supplier_procurement.vendor_slas": {
        'sla_id': 'Unique SLA record ID (SLA-XXXX)',
        'supplier_id': 'FK to suppliers table (SUP-XXX)',
        'supplier_name': 'Supplier company name',
        'sla_metric': 'SLA metric: On_Time_Delivery, Quality_Acceptance, Fill_Rate, Response_Time, Documentation_Accuracy',
        'target_pct': 'Contractual SLA target percentage',
        'actual_pct': 'Actual achieved percentage',
        'variance_pct': 'Variance from target (actual - target). Negative = below target.',
        'is_breached': 'True when actual_pct < target_pct. SLA non-compliance.',
        'penalty_amount': 'Financial penalty in USD for SLA breach. Zero if within target.',
        'review_period': 'SLA review period (e.g., Q3_2026)',
        'last_updated': 'Date SLA was last evaluated (YYYY-MM-DD)',
    },
    f"{CATALOG}.supplier_procurement.procurement_data": {
        'procurement_id': 'Unique procurement record ID (PROC-XXXX)',
        'month': 'First day of month (YYYY-MM-DD)',
        'product_family': 'Product family: Apparel, Accessories, Footwear, Home Goods, Electronics',
        'total_spend_usd': 'Total procurement spend in USD for the month',
        'budgeted_spend_usd': 'Budgeted procurement spend in USD',
        'variance_pct': 'Budget variance %. Positive = over budget.',
        'num_suppliers': 'Number of active suppliers for this product family',
        'num_pos': 'Number of purchase orders placed',
        'avg_unit_cost': 'Average unit cost in USD across all POs',
        'cost_change_mom_pct': 'Month-over-month cost change %. Positive = increasing.',
        'geographic_concentration_risk': 'Geographic sourcing risk: High (Asia-heavy) or Low',
    },
}

total_cols = 0
for table, columns in column_comments.items():
    for col, comment in columns.items():
        safe_comment = comment.replace("'", "\\'")
        spark.sql(f"ALTER TABLE {table} ALTER COLUMN {col} COMMENT '{safe_comment}'")
        total_cols += 1

print(f"✓ {total_cols} column comments applied across {len(column_comments)} tables")
